#VARIABLES
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjA3Y2Y1MWY3NjQ4NDU3OGJhZjc4ZWMiLCJpYXQiOjE3MTE4MDk1ODUsImV4cCI6MTcxMTgxMzE4NX0.jhITmqT4n2g4oQjYgQphyD-e8pz5fzvfhnU36a3Hzv4

#Login
POST http://localhost:3000/api/fithub/users/login
Content-Type: application/json

{
  "email": "torien1227@gmail.com",
  "password": "123"
}


### IL FAUT METTRE 3 ### ENTRE CHAQUE REQUETTE
# Add User
POST http://localhost:3000/api/fithub/users
Content-Type: application/json

{
  "firstname": "Torien",
  "lastname": "-",
  "email": "torien1227@mail.com",
  "password": "123",
  "role": "SUPER_ADMIN",
  "subscription": "abcdef123456"
}

###
# Update User
PUT http://localhost:3000/api/fithub/users/update/6607cf51f76484578baf78ec
Authorization:Bearer {{token}}
Content-Type: application/json

{
  "email": "torien1227@gmail.com"
}

###
# GET All Users
GET http://localhost:3000/api/fithub/users
Authorization:Bearer {{token}}

###
# GET User By id
GET http://localhost:3000/api/fithub/users/6607cf51f76484578baf78ec
Authorization:Bearer {{token}}

###
# GET User By email
GET http://localhost:3000/api/fithub/users/email/torien@mail.com
Authorization:Bearer {{token}}

###
# GET Users By role
GET http://localhost:3000/api/fithub/users/role/SUPER_ADMIN
Authorization:Bearer {{token}}

###
# Deactivte account
PUT http://localhost:3000/api/fithub/users/deactivate/6605e285a5d6c450f40f7ff9
Authorization:Bearer {{token}}

###
# Activte account
PUT http://localhost:3000/api/fithub/users/activate/6605e285a5d6c450f40f7ff9
Authorization:Bearer {{token}}


###
# Delate account
DELETE http://localhost:3000/api/fithub/users/6605f0cbaa3ff5d89ac3ada0
Authorization:Bearer {{token}}

###
# Disconnect account
PUT http://localhost:3000/api/fithub/users/disconnect/6607cf51f76484578baf78ec
Authorization:Bearer {{token}}


### SEND Mail
POST http://localhost:3000/api/fithub/email/send-email
Content-Type: application/json

{
  "to": "torien1227@gmail.com",
  "subject": "Message From app NodeJs project",
  "text":"Texte",
  "html":"<h1>This is just a simple message to test the app.\n Don't answer please</h1>"
}